name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: azure/docker-login@v1
        with:
          login-server: chatgptrepo.azurecr.io
          username: chatGPTRepo
          password: awIYlh8MjP7qGVoAGMRaQ9PZx/QlRuPvdVu6l6BSDg+ACRDTMAgj
      - run: |
          docker build . -t chatgptrepo.azurecr.io/chatGPTRepo:${{ github.sha }}
          docker push chatgptrepo.azurecr.io/chatGPTRepo:${{ github.sha }}
